### ISSUE TITLE
Create release checklist and communication list to corresponding organization.

### ISSUE THREAD

**Issue by faraakhatTW** [PublicDataWorks/complaint-manager#339]
How we know our work was pushed to prod? Hawaii or New Orleans ?
It seems like a big oversight that New Orleans didn't have features we made a month ago & we should discuss how to prevent that from happening again.

- [ ] Create release checklist  for Hawaii and New Orleans 
- [ ] Create communication list to corresponding organization, so everyone on the same page
- [ ] Engage Product Manager so, every documentation is up to date within the team.
