### ISSUE TITLE
Update the checklist for the card template

### ISSUE THREAD

**Issue by rnair-tw** [PublicDataWorks/complaint-manager#501]
Context: The checklist currently in our card templates need to be updated based on a number of things:

- Make sure to add what we did to technical docs (currently in google wiki, future tbd)
- Make sure we update the onboarding trello based on any new things that come up or old things we get rid of

This is the current checklist:

- [ ]  Ensure to include all necessary mockups to this card.
- [ ]  Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
- [ ]  Discuss Feature Flag: Where could a development flag go to flag off incomplete work? Do we want to keep the flag long-term?
- [ ]  If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous cards in the sequence have been finished.
- [ ]  Have we added edge cases as ACs that we're considered from a QA perspective
- [ ]  Should the new functionalities be offered only to users with certain permissions?
- [ ]  How should this functionality differ between different orgs, and if it does differ, what is the hinge point we should use for that functionality?

Proposed checklist:

Kickoff
- [ ] We have we indicated which organizations and user permissions require this 
- [ ] We have indicated whether we have any dependancies to other cards/work
- [ ] We have indicated which environment this can be tested in
- [ ] We have included a mockup if this is design related
- [ ] We have included clear ACs to test it
- [ ] We have estimated the story

Deskcheck
- [ ] This work has been demoed in staging (or higher) and led by the dev pair who worked on this card
- [ ] We have run through and passed all the ACs
- [ ] Our documentation has been updated
- [ ] Our onboarding checklist has been updated

https://github.com/orgs/PublicDataWorks/projects/1/views/1?pane=issue&itemId=48233175

**Comment by rnair-tw** [comment]
Updated the following:
- Template cards
- Cards in ready for dev, in progress and backlog
