### ISSUE TITLE
Come up with Feedback session facilitation structure and discuss ways of giving good feedback

### ISSUE THREAD

**Issue by faraakhatTW** [PublicDataWorks/complaint-manager#577]
### Context
Given that our team has grown in size, it is a good time to review our speedback practice, share helpful tips, and decide on cadence. 

**Goal**: Create a template to be used by team/s

#### Why are speedback sessions useful?
- encourage new members of the team by delivering affirming feedback
- they can be an opportunity to share your personal goals with your teammates. If your teammates have visibility into your growth goals, they can better support you by noticing actions you do on the team that are in alignment with your goals. 
  - For example, if you are looking to become a better presenter, you can share this during speedback. Then if you volunteer to present/facilitate a meeting, the team member you shared this with can take notes and provide you with feedback after, in the next speedback session, in a summit feedback request, etc. 
- allows us to enable and empower our teammates

### Questions
Do we want/need a rotation for speedback?

### References
- [Feedback Playbook](https://docs.google.com/presentation/d/1Ccd1NZ-_P6aAajlVP1TMSU9XdqyCo0hiOy6Q_MitGIw/edit#slide=id.g58a4bf701c_1_211)
- [Speedback 101](https://docs.google.com/presentation/d/1JZQ6rplVdMPP_KTu7Tf5M7EABTNFNr6VdyVFtuhzjUk/edit#slide=id.gc6fa3c898_0_0)
- [How to Give Feedback](https://docs.google.com/presentation/d/1ZmRTBPd9_2VRsOHnrxdKRhDKOyZqdn1gP5CwQz4VLwE/edit#slide=id.g35f391192_04)

### Tasks
- [x] Send meeting invitation for May 9
  - [x] Add agenda
  - [x]  add link/s to useful artifacts
- [x] create google sheet with entire team giving every member of the team feedback (for now)
- [x]  create google doc with feedback/speedback best practices
- [ ] add to `team resources` column on trello
- [x] Prepare speedback 101 learning session a few days before first speedback session
  - [x] send out meeting invitation

**Comment by rd-huerta** [comment]
Started a doc: [Speedback: A How To Guide for Facilitators and Participants](https://docs.google.com/document/d/1rLWhJX9H-z9m5-jIP-UmLt4Y9EB8nA43syHOf41SVGQ/edit#heading=h.39lds9wz752c)

**Comment by rd-huerta** [comment]
Notified team [on slack](https://twatnoipm.slack.com/archives/GJ0B57HPH/p1714676720743279) with more information, including the spreadsheet that contains the pairs for each round.
